version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    volumes:
      - .:/home/node
    command: sh -c "cd nextjs-tsx && npm run dev"
    ports:
      - "3000:3000"