version: '3.9'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      volumes:
      - .:/usr/src/app
    command: sh -c "cd nextjs-tutorial && npm run dev"
    ports:
      - "3000:3000"